### ISSUE TITLE
No `jupyter` directory under `/usr/local/xeus-cling/share`

### ISSUE THREAD

**Issue by sounix000** [pojntfx/xeus-cling-binaries#3]
Hi @pojntfx,

I am using Fedora 34, and I have problems installing the C++ kernels. To be specific, when I executed `sudo jupyter kernelspec install ${XEUS_PREFIX}/share/jupyter/kernels/xcpp11 --sys-prefix`, the error was as follows:
```
[sosarkar@fedora ~]$ sudo jupyter kernelspec install ${XEUS_PREFIX}/share/jupyter/kernels/xcpp11 --sys-prefix
Traceback (most recent call last):
  File "/usr/bin/jupyter-kernelspec", line 8, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/lib/python3.9/site-packages/jupyter_client/kernelspecapp.py", line 266, in start
    return self.subapp.start()
  File "/usr/lib/python3.9/site-packages/jupyter_client/kernelspecapp.py", line 132, in start
    self.kernel_spec_manager.install_kernel_spec(self.sourcedir,
  File "/usr/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 345, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib64/python3.9/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/xeus-cling/share/jupyter/kernels/xcpp11'
```

The same error occurred when I tried using `--user` instead of `--sys-prefix`.

I checked and there is no `jupyter` directory under `/usr/local/xeus-cling/share`:
```
[sosarkar@fedora ~]$ ls /usr/local/xeus-cling/share/ -l
total 0
drwxr-xr-x. 1 root root  16 Oct 17 06:43 aclocal
drwxr-xr-x. 1 root root  22 Oct 17 06:43 bash-completion
drwxr-xr-x. 1 root root 330 Oct 17 06:43 clang
drwxr-xr-x. 1 root root  18 Oct 17 06:43 cmake
drwxr-xr-x. 1 root root  54 Oct 17 06:43 cmake-3.21
drwxr-xr-x. 1 root root  58 Oct 17 06:43 doc
drwxr-xr-x. 1 root root  18 Oct 17 06:43 emacs
drwxr-xr-x. 1 root root  32 Oct 17 06:43 et
drwxr-xr-x. 1 root root   8 Oct 17 06:43 examples
drwxr-xr-x. 1 root root  12 Oct 17 06:43 gcc-9.4.0
drwxr-xr-x. 1 root root 246 Oct 17 06:43 info
drwxr-xr-x. 1 root root  84 Oct 17 06:43 licenses
drwxr-xr-x. 1 root root  76 Oct 17 06:43 locale
drwxr-xr-x. 1 root root  44 Oct 17 06:43 man
drwxr-xr-x. 1 root root  38 Oct 17 06:43 nghttp2
drwxr-xr-x. 1 root root 156 Oct 17 06:43 opt-viewer
drwxr-xr-x. 1 root root  12 Oct 17 06:43 pkgconfig
drwxr-xr-x. 1 root root  48 Oct 17 06:43 scan-build
drwxr-xr-x. 1 root root 186 Oct 17 06:43 scan-view
drwxr-xr-x. 1 root root  38 Oct 17 06:40 tabset
drwxr-xr-x. 1 root root  84 Oct 17 06:40 terminfo
drwxr-xr-x. 1 root root  16 Oct 17 06:43 vim
drwxr-xr-x. 1 root root 768 Oct 17 06:40 zoneinfo
```

The binaries were working perfectly after the patch for [issue #2](https://github.com/pojntfx/xeus-cling-binaries/issues/2). I am wondering what changed between then and now, and how is the CI passing if any major change has been made.

I would appreciate any help regarding this issue.

**Note**: Same error occurs for the [SQL binaries](https://github.com/pojntfx/xeus-cling-binaries) too.

**Comment by bd4** [comment]
I am running into this too. Search for jupyter in the unpacked xeus-cling dir, I only find `pkgs/cling-0.8-hf817b99_1/info/recipe/patches/0001-remove-jupyter.patch`, so it appears this was intentionally removed?

**Comment by illegalplumbing** [comment]
+1

**Comment by formoon** [comment]
+1
